### ISSUE TITLE
Add and config a git branch for github pages

### ISSUE THREAD

**Issue by canhnd58** [canhnd58/duosnake#10]
Automatically build and deploy to github pages after pushing a commit to master branch.

**Comment by canhnd58** [comment]
Found something that could be used:
- [github actions](https://github.com/features/actions)
- [Deploy to github pages](https://github.com/marketplace/actions/deploy-to-github-pages)

**Comment by tung-eh** [comment]
I added some config to auto-run build command while push to master, but currently the github page isn't using the build folder to serve. Seems like it need to be updated from `Settings`, could you help with changing @canhnd58 , the build folder is `dist/` FYI.

**Comment by canhnd58** [comment]
@tung-eh  The only folders github pages may use as root dir are `/` or `/docs` of branch `master` or `gh-pages`. I can only choose among these in the Settings. More importantly, the serving files should be present in the codebase but I don't see any folders `dist/` there (and it should not be there).

I think we need to add one more action to `.github/workflows/node.js.yml` after building to copy the result to branch `gh-pages`.

**Comment by tung-eh** [comment]
Updated! The branch to deploy will be `gh-pages` from now.
