### ISSUE TITLE
Split source codes into files and add a build tool

### ISSUE THREAD

**Issue by canhnd58** [canhnd58/duosnake#9]

**Comment by tung-eh** [comment]
I suggest using [Vite](https://vitejs.dev/) (French word - pronounced /vit/) - a new/modern build tool, blazing fast, easy to setup (ez af I swear). 

If we agree on this, I can help a hand to setup.

**Comment by canhnd58** [comment]
This makes Issue #10 more urgent.

**Comment by canhnd58** [comment]
Can you split `main.js` into at least 2 files and/or folders for those unfamiliar with Vite (me) to know how to continue coding?

**Comment by tung-eh** [comment]
@canhnd58 Vite using ES module syntax, it means we can use `import`/`export` to communicate between modules.

For example
```javascript
// foo.js

const a = 'a string'
const b = 'another string'

export { a }
export default b
```

```javascript
// bar.js

import { a }, b from './foo' /* Let's say foo.js is in the same dir with bar.js */
```

**Comment by canhnd58** [comment]
@tung-eh  `npm run serve` does not work locally because it searches for resources in `https://canhnd58.github.io/duosnake/`.
Should we fix it or just remove the commands from `package.json`?

**Comment by tung-eh** [comment]
I removed the hostname from the `base` config through this [commit](f5343c0ef95da05d7017ef33f497b8aa6f6479ef). It should works fine from now.

**Comment by canhnd58** [comment]
It works perfectly now. 10 billion points.
